services:
  - type: web
    name: swigato
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn project1.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: project1.settings
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "swigato.onrender.com"
