# Generated by Django 5.1.1 on 2024-10-01 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0009_items_delete_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='image',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='price',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='rating',
            new_name='Rating',
        ),
    ]
