# Generated by Django 5.1.1 on 2024-10-01 07:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0010_rename_description_items_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='Item_ID',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
