# Generated by Django 5.1.1 on 2024-10-02 18:29

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0013_restaurant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
            preserve_default=False,
        ),
    ]
