# Generated by Django 5.1.1 on 2024-10-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0015_menuitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='rating',
            field=models.FloatField(),
        ),
    ]
